// Complete list of all countries and international dialing codes in the world
// ISO 3166-1 alpha-2 standard and ITU-T E.164 international calling codes

export interface CountryDialCode {
  name: string;
  code: string;
  iso: string;
  label: string;
}

export const ALL_COUNTRY_DIAL_CODES: CountryDialCode[] = [
  // Southern & Eastern Africa priority defaults
  { name: "South Africa", code: "+27", iso: "ZA", label: "South Africa (+27)" },
  { name: "Namibia", code: "+264", iso: "NA", label: "Namibia (+264)" },
  { name: "Zimbabwe", code: "+263", iso: "ZW", label: "Zimbabwe (+263)" },
  { name: "Botswana", code: "+267", iso: "BW", label: "Botswana (+267)" },
  { name: "Zambia", code: "+260", iso: "ZM", label: "Zambia (+260)" },
  { name: "Mozambique", code: "+258", iso: "MZ", label: "Mozambique (+258)" },
  { name: "Angola", code: "+244", iso: "AO", label: "Angola (+244)" },
  { name: "Kenya", code: "+254", iso: "KE", label: "Kenya (+254)" },
  { name: "Tanzania", code: "+255", iso: "TZ", label: "Tanzania (+255)" },
  { name: "Uganda", code: "+256", iso: "UG", label: "Uganda (+256)" },
  { name: "Rwanda", code: "+250", iso: "RW", label: "Rwanda (+250)" },
  { name: "Nigeria", code: "+234", iso: "NG", label: "Nigeria (+234)" },
  { name: "Ghana", code: "+233", iso: "GH", label: "Ghana (+233)" },
  { name: "United Kingdom", code: "+44", iso: "GB", label: "United Kingdom (+44)" },
  { name: "United States", code: "+1", iso: "US", label: "United States (+1)" },
  { name: "Canada", code: "+1", iso: "CA", label: "Canada (+1)" },
  { name: "Australia", code: "+61", iso: "AU", label: "Australia (+61)" },
  { name: "Germany", code: "+49", iso: "DE", label: "Germany (+49)" },
  { name: "United Arab Emirates", code: "+971", iso: "AE", label: "United Arab Emirates (+971)" },
  { name: "India", code: "+91", iso: "IN", label: "India (+91)" },

  // Complete Alphabetical Directory of All Countries in the World
  { name: "Afghanistan", code: "+93", iso: "AF", label: "Afghanistan (+93)" },
  { name: "Albania", code: "+355", iso: "AL", label: "Albania (+355)" },
  { name: "Algeria", code: "+213", iso: "DZ", label: "Algeria (+213)" },
  { name: "American Samoa", code: "+1684", iso: "AS", label: "American Samoa (+1684)" },
  { name: "Andorra", code: "+376", iso: "AD", label: "Andorra (+376)" },
  { name: "Anguilla", code: "+1264", iso: "AI", label: "Anguilla (+1264)" },
  { name: "Antigua and Barbuda", code: "+1268", iso: "AG", label: "Antigua and Barbuda (+1268)" },
  { name: "Argentina", code: "+54", iso: "AR", label: "Argentina (+54)" },
  { name: "Armenia", code: "+374", iso: "AM", label: "Armenia (+374)" },
  { name: "Aruba", code: "+297", iso: "AW", label: "Aruba (+297)" },
  { name: "Austria", code: "+43", iso: "AT", label: "Austria (+43)" },
  { name: "Azerbaijan", code: "+994", iso: "AZ", label: "Azerbaijan (+994)" },
  { name: "Bahamas", code: "+1242", iso: "BS", label: "Bahamas (+1242)" },
  { name: "Bahrain", code: "+973", iso: "BH", label: "Bahrain (+973)" },
  { name: "Bangladesh", code: "+880", iso: "BD", label: "Bangladesh (+880)" },
  { name: "Barbados", code: "+1246", iso: "BB", label: "Barbados (+1246)" },
  { name: "Belarus", code: "+375", iso: "BY", label: "Belarus (+375)" },
  { name: "Belgium", code: "+32", iso: "BE", label: "Belgium (+32)" },
  { name: "Belize", code: "+501", iso: "BZ", label: "Belize (+501)" },
  { name: "Benin", code: "+229", iso: "BJ", label: "Benin (+229)" },
  { name: "Bermuda", code: "+1441", iso: "BM", label: "Bermuda (+1441)" },
  { name: "Bhutan", code: "+975", iso: "BT", label: "Bhutan (+975)" },
  { name: "Bolivia", code: "+591", iso: "BO", label: "Bolivia (+591)" },
  { name: "Bosnia and Herzegovina", code: "+387", iso: "BA", label: "Bosnia and Herzegovina (+387)" },
  { name: "Brazil", code: "+55", iso: "BR", label: "Brazil (+55)" },
  { name: "British Virgin Islands", code: "+1284", iso: "VG", label: "British Virgin Islands (+1284)" },
  { name: "Brunei", code: "+673", iso: "BN", label: "Brunei (+673)" },
  { name: "Bulgaria", code: "+359", iso: "BG", label: "Bulgaria (+359)" },
  { name: "Burkina Faso", code: "+226", iso: "BF", label: "Burkina Faso (+226)" },
  { name: "Burundi", code: "+257", iso: "BI", label: "Burundi (+257)" },
  { name: "Cambodia", code: "+855", iso: "KH", label: "Cambodia (+855)" },
  { name: "Cameroon", code: "+237", iso: "CM", label: "Cameroon (+237)" },
  { name: "Cape Verde", code: "+238", iso: "CV", label: "Cape Verde (+238)" },
  { name: "Cayman Islands", code: "+1345", iso: "KY", label: "Cayman Islands (+1345)" },
  { name: "Central African Republic", code: "+236", iso: "CF", label: "Central African Republic (+236)" },
  { name: "Chad", code: "+235", iso: "TD", label: "Chad (+235)" },
  { name: "Chile", code: "+56", iso: "CL", label: "Chile (+56)" },
  { name: "China", code: "+86", iso: "CN", label: "China (+86)" },
  { name: "Colombia", code: "+57", iso: "CO", label: "Colombia (+57)" },
  { name: "Comoros", code: "+269", iso: "KM", label: "Comoros (+269)" },
  { name: "Congo (Brazzaville)", code: "+242", iso: "CG", label: "Congo (Brazzaville) (+242)" },
  { name: "Congo (Kinshasa - DRC)", code: "+243", iso: "CD", label: "Congo (Kinshasa - DRC) (+243)" },
  { name: "Cook Islands", code: "+682", iso: "CK", label: "Cook Islands (+682)" },
  { name: "Costa Rica", code: "+506", iso: "CR", label: "Costa Rica (+506)" },
  { name: "Croatia", code: "+385", iso: "HR", label: "Croatia (+385)" },
  { name: "Cuba", code: "+53", iso: "CU", label: "Cuba (+53)" },
  { name: "Curaçao", code: "+599", iso: "CW", label: "Curaçao (+599)" },
  { name: "Cyprus", code: "+357", iso: "CY", label: "Cyprus (+357)" },
  { name: "Czech Republic", code: "+420", iso: "CZ", label: "Czech Republic (+420)" },
  { name: "Denmark", code: "+45", iso: "DK", label: "Denmark (+45)" },
  { name: "Djibouti", code: "+253", iso: "DJ", label: "Djibouti (+253)" },
  { name: "Dominica", code: "+1767", iso: "DM", label: "Dominica (+1767)" },
  { name: "Dominican Republic", code: "+1809", iso: "DO", label: "Dominican Republic (+1809)" },
  { name: "Ecuador", code: "+593", iso: "EC", label: "Ecuador (+593)" },
  { name: "Egypt", code: "+20", iso: "EG", label: "Egypt (+20)" },
  { name: "El Salvador", code: "+503", iso: "SV", label: "El Salvador (+503)" },
  { name: "Equatorial Guinea", code: "+240", iso: "GQ", label: "Equatorial Guinea (+240)" },
  { name: "Eritrea", code: "+291", iso: "ER", label: "Eritrea (+291)" },
  { name: "Estonia", code: "+372", iso: "EE", label: "Estonia (+372)" },
  { name: "Eswatini (Swaziland)", code: "+268", iso: "SZ", label: "Eswatini (Swaziland) (+268)" },
  { name: "Ethiopia", code: "+251", iso: "ET", label: "Ethiopia (+251)" },
  { name: "Falkland Islands", code: "+500", iso: "FK", label: "Falkland Islands (+500)" },
  { name: "Faroe Islands", code: "+298", iso: "FO", label: "Faroe Islands (+298)" },
  { name: "Fiji", code: "+679", iso: "FJ", label: "Fiji (+679)" },
  { name: "Finland", code: "+358", iso: "FI", label: "Finland (+358)" },
  { name: "France", code: "+33", iso: "FR", label: "France (+33)" },
  { name: "French Guiana", code: "+594", iso: "GF", label: "French Guiana (+594)" },
  { name: "French Polynesia", code: "+689", iso: "PF", label: "French Polynesia (+689)" },
  { name: "Gabon", code: "+241", iso: "GA", label: "Gabon (+241)" },
  { name: "Gambia", code: "+220", iso: "GM", label: "Gambia (+220)" },
  { name: "Georgia", code: "+995", iso: "GE", label: "Georgia (+995)" },
  { name: "Gibraltar", code: "+350", iso: "GI", label: "Gibraltar (+350)" },
  { name: "Greece", code: "+30", iso: "GR", label: "Greece (+30)" },
  { name: "Greenland", code: "+299", iso: "GL", label: "Greenland (+299)" },
  { name: "Grenada", code: "+1473", iso: "GD", label: "Grenada (+1473)" },
  { name: "Guadeloupe", code: "+590", iso: "GP", label: "Guadeloupe (+590)" },
  { name: "Guam", code: "+1671", iso: "GU", label: "Guam (+1671)" },
  { name: "Guatemala", code: "+502", iso: "GT", label: "Guatemala (+502)" },
  { name: "Guinea", code: "+224", iso: "GN", label: "Guinea (+224)" },
  { name: "Guinea-Bissau", code: "+245", iso: "GW", label: "Guinea-Bissau (+245)" },
  { name: "Guyana", code: "+592", iso: "GY", label: "Guyana (+592)" },
  { name: "Haiti", code: "+509", iso: "HT", label: "Haiti (+509)" },
  { name: "Honduras", code: "+504", iso: "HN", label: "Honduras (+504)" },
  { name: "Hong Kong", code: "+852", iso: "HK", label: "Hong Kong (+852)" },
  { name: "Hungary", code: "+36", iso: "HU", label: "Hungary (+36)" },
  { name: "Iceland", code: "+354", iso: "IS", label: "Iceland (+354)" },
  { name: "Indonesia", code: "+62", iso: "ID", label: "Indonesia (+62)" },
  { name: "Iran", code: "+98", iso: "IR", label: "Iran (+98)" },
  { name: "Iraq", code: "+964", iso: "IQ", label: "Iraq (+964)" },
  { name: "Ireland", code: "+353", iso: "IE", label: "Ireland (+353)" },
  { name: "Isle of Man", code: "+44", iso: "IM", label: "Isle of Man (+44)" },
  { name: "Israel", code: "+972", iso: "IL", label: "Israel (+972)" },
  { name: "Italy", code: "+39", iso: "IT", label: "Italy (+39)" },
  { name: "Ivory Coast (Côte d'Ivoire)", code: "+225", iso: "CI", label: "Ivory Coast (+225)" },
  { name: "Jamaica", code: "+1876", iso: "JM", label: "Jamaica (+1876)" },
  { name: "Japan", code: "+81", iso: "JP", label: "Japan (+81)" },
  { name: "Jordan", code: "+962", iso: "JO", label: "Jordan (+962)" },
  { name: "Kazakhstan", code: "+7", iso: "KZ", label: "Kazakhstan (+7)" },
  { name: "Kiribati", code: "+686", iso: "KI", label: "Kiribati (+686)" },
  { name: "Kosovo", code: "+383", iso: "XK", label: "Kosovo (+383)" },
  { name: "Kuwait", code: "+965", iso: "KW", label: "Kuwait (+965)" },
  { name: "Kyrgyzstan", code: "+996", iso: "KG", label: "Kyrgyzstan (+996)" },
  { name: "Laos", code: "+856", iso: "LA", label: "Laos (+856)" },
  { name: "Latvia", code: "+371", iso: "LV", label: "Latvia (+371)" },
  { name: "Lebanon", code: "+961", iso: "LB", label: "Lebanon (+961)" },
  { name: "Lesotho", code: "+266", iso: "LS", label: "Lesotho (+266)" },
  { name: "Liberia", code: "+231", iso: "LR", label: "Liberia (+231)" },
  { name: "Libya", code: "+218", iso: "LY", label: "Libya (+218)" },
  { name: "Liechtenstein", code: "+423", iso: "LI", label: "Liechtenstein (+423)" },
  { name: "Lithuania", code: "+370", iso: "LT", label: "Lithuania (+370)" },
  { name: "Luxembourg", code: "+352", iso: "LU", label: "Luxembourg (+352)" },
  { name: "Macao", code: "+853", iso: "MO", label: "Macao (+853)" },
  { name: "Madagascar", code: "+261", iso: "MG", label: "Madagascar (+261)" },
  { name: "Malawi", code: "+265", iso: "MW", label: "Malawi (+265)" },
  { name: "Malaysia", code: "+60", iso: "MY", label: "Malaysia (+60)" },
  { name: "Maldives", code: "+960", iso: "MV", label: "Maldives (+960)" },
  { name: "Mali", code: "+223", iso: "ML", label: "Mali (+223)" },
  { name: "Malta", code: "+356", iso: "MT", label: "Malta (+356)" },
  { name: "Marshall Islands", code: "+692", iso: "MH", label: "Marshall Islands (+692)" },
  { name: "Martinique", code: "+596", iso: "MQ", label: "Martinique (+596)" },
  { name: "Mauritania", code: "+222", iso: "MR", label: "Mauritania (+222)" },
  { name: "Mauritius", code: "+230", iso: "MU", label: "Mauritius (+230)" },
  { name: "Mayotte", code: "+262", iso: "YT", label: "Mayotte (+262)" },
  { name: "Mexico", code: "+52", iso: "MX", label: "Mexico (+52)" },
  { name: "Micronesia", code: "+691", iso: "FM", label: "Micronesia (+691)" },
  { name: "Moldova", code: "+373", iso: "MD", label: "Moldova (+373)" },
  { name: "Monaco", code: "+377", iso: "MC", label: "Monaco (+377)" },
  { name: "Mongolia", code: "+976", iso: "MN", label: "Mongolia (+976)" },
  { name: "Montenegro", code: "+382", iso: "ME", label: "Montenegro (+382)" },
  { name: "Montserrat", code: "+1664", iso: "MS", label: "Montserrat (+1664)" },
  { name: "Morocco", code: "+212", iso: "MA", label: "Morocco (+212)" },
  { name: "Myanmar (Burma)", code: "+95", iso: "MM", label: "Myanmar (Burma) (+95)" },
  { name: "Nauru", code: "+674", iso: "NR", label: "Nauru (+674)" },
  { name: "Nepal", code: "+977", iso: "NP", label: "Nepal (+977)" },
  { name: "Netherlands", code: "+31", iso: "NL", label: "Netherlands (+31)" },
  { name: "New Caledonia", code: "+687", iso: "NC", label: "New Caledonia (+687)" },
  { name: "New Zealand", code: "+64", iso: "NZ", label: "New Zealand (+64)" },
  { name: "Nicaragua", code: "+505", iso: "NI", label: "Nicaragua (+505)" },
  { name: "Niger", code: "+227", iso: "NE", label: "Niger (+227)" },
  { name: "North Korea", code: "+850", iso: "KP", label: "North Korea (+850)" },
  { name: "North Macedonia", code: "+389", iso: "MK", label: "North Macedonia (+389)" },
  { name: "Northern Mariana Islands", code: "+1670", iso: "MP", label: "Northern Mariana Islands (+1670)" },
  { name: "Norway", code: "+47", iso: "NO", label: "Norway (+47)" },
  { name: "Oman", code: "+968", iso: "OM", label: "Oman (+968)" },
  { name: "Pakistan", code: "+92", iso: "PK", label: "Pakistan (+92)" },
  { name: "Palau", code: "+680", iso: "PW", label: "Palau (+680)" },
  { name: "Palestine", code: "+970", iso: "PS", label: "Palestine (+970)" },
  { name: "Panama", code: "+507", iso: "PA", label: "Panama (+507)" },
  { name: "Papua New Guinea", code: "+675", iso: "PG", label: "Papua New Guinea (+675)" },
  { name: "Paraguay", code: "+595", iso: "PY", label: "Paraguay (+595)" },
  { name: "Peru", code: "+51", iso: "PE", label: "Peru (+51)" },
  { name: "Philippines", code: "+63", iso: "PH", label: "Philippines (+63)" },
  { name: "Poland", code: "+48", iso: "PL", label: "Poland (+48)" },
  { name: "Portugal", code: "+351", iso: "PT", label: "Portugal (+351)" },
  { name: "Puerto Rico", code: "+1787", iso: "PR", label: "Puerto Rico (+1787)" },
  { name: "Qatar", code: "+974", iso: "QA", label: "Qatar (+974)" },
  { name: "Réunion", code: "+262", iso: "RE", label: "Réunion (+262)" },
  { name: "Romania", code: "+40", iso: "RO", label: "Romania (+40)" },
  { name: "Russia", code: "+7", iso: "RU", label: "Russia (+7)" },
  { name: "Saint Barthélemy", code: "+590", iso: "BL", label: "Saint Barthélemy (+590)" },
  { name: "Saint Helena", code: "+290", iso: "SH", label: "Saint Helena (+290)" },
  { name: "Saint Kitts and Nevis", code: "+1869", iso: "KN", label: "Saint Kitts and Nevis (+1869)" },
  { name: "Saint Lucia", code: "+1758", iso: "LC", label: "Saint Lucia (+1758)" },
  { name: "Saint Martin", code: "+590", iso: "MF", label: "Saint Martin (+590)" },
  { name: "Saint Pierre and Miquelon", code: "+508", iso: "PM", label: "Saint Pierre and Miquelon (+508)" },
  { name: "Saint Vincent and the Grenadines", code: "+1784", iso: "VC", label: "Saint Vincent & Grenadines (+1784)" },
  { name: "Samoa", code: "+685", iso: "WS", label: "Samoa (+685)" },
  { name: "San Marino", code: "+378", iso: "SM", label: "San Marino (+378)" },
  { name: "Sao Tome and Principe", code: "+239", iso: "ST", label: "Sao Tome and Principe (+239)" },
  { name: "Saudi Arabia", code: "+966", iso: "SA", label: "Saudi Arabia (+966)" },
  { name: "Senegal", code: "+221", iso: "SN", label: "Senegal (+221)" },
  { name: "Serbia", code: "+381", iso: "RS", label: "Serbia (+381)" },
  { name: "Seychelles", code: "+248", iso: "SC", label: "Seychelles (+248)" },
  { name: "Sierra Leone", code: "+232", iso: "SL", label: "Sierra Leone (+232)" },
  { name: "Singapore", code: "+65", iso: "SG", label: "Singapore (+65)" },
  { name: "Sint Maarten", code: "+1721", iso: "SX", label: "Sint Maarten (+1721)" },
  { name: "Slovakia", code: "+421", iso: "SK", label: "Slovakia (+421)" },
  { name: "Slovenia", code: "+386", iso: "SI", label: "Slovenia (+386)" },
  { name: "Solomon Islands", code: "+677", iso: "SB", label: "Solomon Islands (+677)" },
  { name: "Somalia", code: "+252", iso: "SO", label: "Somalia (+252)" },
  { name: "South Korea", code: "+82", iso: "KR", label: "South Korea (+82)" },
  { name: "South Sudan", code: "+211", iso: "SS", label: "South Sudan (+211)" },
  { name: "Spain", code: "+34", iso: "ES", label: "Spain (+34)" },
  { name: "Sri Lanka", code: "+94", iso: "LK", label: "Sri Lanka (+94)" },
  { name: "Sudan", code: "+249", iso: "SD", label: "Sudan (+249)" },
  { name: "Suriname", code: "+597", iso: "SR", label: "Suriname (+597)" },
  { name: "Sweden", code: "+46", iso: "SE", label: "Sweden (+46)" },
  { name: "Switzerland", code: "+41", iso: "CH", label: "Switzerland (+41)" },
  { name: "Syria", code: "+963", iso: "SY", label: "Syria (+963)" },
  { name: "Taiwan", code: "+886", iso: "TW", label: "Taiwan (+886)" },
  { name: "Tajikistan", code: "+992", iso: "TJ", label: "Tajikistan (+992)" },
  { name: "Thailand", code: "+66", iso: "TH", label: "Thailand (+66)" },
  { name: "Timor-Leste", code: "+670", iso: "TL", label: "Timor-Leste (+670)" },
  { name: "Togo", code: "+228", iso: "TG", label: "Togo (+228)" },
  { name: "Tokelau", code: "+690", iso: "TK", label: "Tokelau (+690)" },
  { name: "Tonga", code: "+676", iso: "TO", label: "Tonga (+676)" },
  { name: "Trinidad and Tobago", code: "+1868", iso: "TT", label: "Trinidad and Tobago (+1868)" },
  { name: "Tunisia", code: "+216", iso: "TN", label: "Tunisia (+216)" },
  { name: "Turkey", code: "+90", iso: "TR", label: "Turkey (+90)" },
  { name: "Turkmenistan", code: "+993", iso: "TM", label: "Turkmenistan (+993)" },
  { name: "Turks and Caicos Islands", code: "+1649", iso: "TC", label: "Turks and Caicos Islands (+1649)" },
  { name: "Tuvalu", code: "+688", iso: "TV", label: "Tuvalu (+688)" },
  { name: "Ukraine", code: "+380", iso: "UA", label: "Ukraine (+380)" },
  { name: "Uruguay", code: "+598", iso: "UY", label: "Uruguay (+598)" },
  { name: "Uzbekistan", code: "+998", iso: "UZ", label: "Uzbekistan (+998)" },
  { name: "Vanuatu", code: "+678", iso: "VU", label: "Vanuatu (+678)" },
  { name: "Vatican City", code: "+379", iso: "VA", label: "Vatican City (+379)" },
  { name: "Venezuela", code: "+58", iso: "VE", label: "Venezuela (+58)" },
  { name: "Vietnam", code: "+84", iso: "VN", label: "Vietnam (+84)" },
  { name: "US Virgin Islands", code: "+1340", iso: "VI", label: "US Virgin Islands (+1340)" },
  { name: "Wallis and Futuna", code: "+681", iso: "WF", label: "Wallis and Futuna (+681)" },
  { name: "Yemen", code: "+967", iso: "YE", label: "Yemen (+967)" },
];
