import React, { useState } from "react";
import { Modal } from "@/components/modal";
import { ShieldCheck, Scale, AlertTriangle, FileText, CheckCircle2, X } from "lucide-react";

export const TERMS_AND_CONDITIONS_VERSION = "2026.1";

export const TERMS_AND_CONDITIONS_SECTIONS = [
  {
    title: "1. Nature of the Service: Software Platform Provider Only (Strict Non-Agency)",
    content: `This system, platform, and application ("the Platform") is exclusively an independent multi-tenant enterprise software and cloud management solution. We are strictly a technology and software provider. 

Under no circumstances does the Platform, its developers, operators, parent entities, or affiliates act as a real estate agent, estate agency, property broker, leasing broker, property manager, escrow holder, hospitality operator, or financial custodian. 

The Platform does not inspect properties, verify physical ownership, broker sales or rental agreements, negotiate transactions, hold client funds, or represent any buyer, seller, landlord, tenant, or guest. All contractual, commercial, hospitality, and rental transactions conducted or recorded using this software exist solely and exclusively between the registered operating organization and its respective clients, guests, or tenants.`,
  },
  {
    title: "2. Mandatory Statutory Licensing & Regulatory Compliance Warranty",
    content: `By registering an organization, creating a user profile, advertising any room or property, issuing a contract or invoice, or utilizing the Agent Mode / Hospitality modules, you explicitly, unconditionally warrant and covenant that:

a) You and your organization operate in full and strict compliance with all local, regional, provincial, state, and national laws, regulations, statutes, and municipal bylaws of each country and jurisdiction in which you advertise, lease, sell, or manage properties.
b) You and your business entity possess all valid, unexpired, legally required statutory licenses, regulatory registrations, and fidelity fund certificates—including, without limitation, Property Practitioners Regulatory Authority (PPRA) accreditation, Estate Agency Affairs Board certifications, Hospitality Operating Permits, Hotel & Lodge Lodging licenses, VAT/Tax registrations, and municipal health & safety certificates.
c) Operating or advertising any real estate listing, tenancy, or hospitality lodging without the requisite statutory licenses and authority is strictly prohibited and constitutes an immediate material breach of these Terms.`,
  },
  {
    title: "3. Direct Civil and Criminal Liability for Unlicensed Activities",
    content: `Anyone who signs up, registers, or advertises on this system without holding the mandatory statutory credentials or licenses will face direct civil and criminal legal charges initiated by the relevant government bodies, statutory boards, consumer protection agencies, and law enforcement authorities of that jurisdiction.

The Platform explicitly cooperates with lawful subpoenas, regulatory audits, and law enforcement investigations, and reserves the right to immediately suspend, terminate, and report any account found to be operating fraudulently or without requisite statutory licenses.`,
  },
  {
    title: "4. Complete Indemnification of the Software Provider",
    content: `You agree to irrevocably indemnify, defend, and hold completely harmless the Platform, its directors, officers, software engineers, affiliates, and hosting infrastructure providers from and against any and all claims, liabilities, lawsuits, disputes, regulatory fines, civil actions, damages, loss of profits, or legal expenses (including attorney fees on an attorney-and-own-client scale) arising directly or indirectly from:

a) Any listing, property advertisement, sale, or lease initiated, published, or concluded by you or your staff;
b) Any misrepresentation, error, omission, or dispute regarding property features, prices, availability, or condition;
c) Any guest dispute, tenant eviction, injury, damage to premises, or security deposit disagreement;
d) Any failure by you or your organization to abide by the statutory licensing, taxation, employment, or housing laws of your operating country.`,
  },
  {
    title: "5. Content, Photography & Data Accuracy Warranties",
    content: `You represent and warrant that you hold full legal copyright, ownership, or authorized client mandate for all media, photographs, specifications, documentation, and pricing uploaded to the Platform (including room showcases, stores receipts, and property listings). You agree never to upload misleading, unauthorized, fraudulent, or infringing media.`,
  },
  {
    title: "6. Autonomous Taxation & Remittance Responsibilities",
    content: `All invoices, receipts, payslips, and tax calculations generated by the Platform are automated based upon the parameters, billing currency, and tax rates configured by the operating organization's administrators. The Platform accepts no liability for errors in tax withholding, VAT submissions, PAYE, or regulatory fiscal filings. The operating organization assumes sole responsibility for audit accuracy and compliance with national revenue services.`,
  },
];

interface TermsModalProps {
  open: boolean;
  onClose: () => void;
  onAccept?: () => void;
  showAcceptButton?: boolean;
}

export function TermsModal({ open, onClose, onAccept, showAcceptButton = false }: TermsModalProps) {
  return (
    <Modal open={open} onClose={onClose} title="Platform Terms of Service & Regulatory Compliance">
      <div className="space-y-4 max-h-[65vh] overflow-y-auto pr-2 text-xs text-foreground/90 leading-relaxed">
        {/* Highlight Banner */}
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3.5 space-y-1 text-amber-800 dark:text-amber-300">
          <div className="flex items-center gap-2 font-bold text-sm">
            <Scale size={18} className="shrink-0 text-amber-600 dark:text-amber-400" />
            <span>Software Provider Disclaimer & Mandatory Licensing Notice</span>
          </div>
          <p className="text-[11px] leading-normal opacity-90">
            We are exclusively an independent technology software provider and NOT a real estate or rental agency. All subscribers must hold valid statutory estate agency / hospitality licenses under the laws of their operating country or face immediate legal charges.
          </p>
        </div>

        {/* Section Blocks */}
        <div className="space-y-4 divide-y divide-border-color/60">
          {TERMS_AND_CONDITIONS_SECTIONS.map((section, idx) => (
            <div key={idx} className={idx > 0 ? "pt-3.5 space-y-1.5" : "space-y-1.5"}>
              <h4 className="font-bold text-sm text-foreground flex items-center gap-1.5">
                <FileText size={14} className="text-blue-600 shrink-0" />
                <span>{section.title}</span>
              </h4>
              <p className="text-xs text-muted whitespace-pre-line leading-relaxed">
                {section.content}
              </p>
            </div>
          ))}
        </div>

        <div className="rounded-xl border border-border-color bg-surface-elevated/60 p-3 text-[11px] text-muted">
          <p>
            <strong>Version:</strong> {TERMS_AND_CONDITIONS_VERSION} &middot; Effective Date: Active immediately upon account registration or platform usage.
          </p>
        </div>
      </div>

      {/* Footer Controls */}
      <div className="flex items-center justify-between border-t border-border-color pt-3 mt-3">
        <button
          type="button"
          onClick={onClose}
          className="rounded-xl border border-border-color bg-surface-elevated px-4 py-2 text-xs font-semibold text-foreground hover:bg-surface-elevated/70 transition"
        >
          Close
        </button>

        {showAcceptButton && onAccept && (
          <button
            type="button"
            onClick={() => {
              onAccept();
              onClose();
            }}
            className="flex items-center gap-1.5 rounded-xl bg-blue-600 px-5 py-2 text-xs font-bold text-white shadow-md hover:bg-blue-700 transition"
          >
            <CheckCircle2 size={14} />
            <span>I Understand & Agree</span>
          </button>
        )}
      </div>
    </Modal>
  );
}

interface TermsCheckboxFieldProps {
  checked: boolean;
  onChange: (checked: boolean) => void;
  required?: boolean;
}

export function TermsCheckboxField({ checked, onChange, required = true }: TermsCheckboxFieldProps) {
  const [modalOpen, setModalOpen] = useState(false);

  return (
    <div className="space-y-2">
      <label className="flex items-start gap-2.5 cursor-pointer select-none text-xs text-foreground/90">
        <input
          type="checkbox"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
          required={required}
          className="mt-0.5 h-4 w-4 rounded border-border-color text-blue-600 focus:ring-blue-500 cursor-pointer shrink-0"
        />
        <span className="leading-snug">
          I have read, understood, and agree to the{" "}
          <button
            type="button"
            onClick={(e) => {
              e.preventDefault();
              setModalOpen(true);
            }}
            className="font-bold text-blue-600 underline hover:text-blue-700"
          >
            Platform Terms of Service & Statutory Licensing Policy
          </button>
          . I certify that our organization is the legal operator, holds all valid professional licenses required by local law, and acknowledges that this platform acts strictly as an independent software provider.
        </span>
      </label>

      <TermsModal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        showAcceptButton={true}
        onAccept={() => onChange(true)}
      />
    </div>
  );
}

